# Matriz Extendida
<!--## Aplicaciones
## Equivalencia con sistema de ecuacioes
## E1 a E4
## Operaciones elementales
## Algoritmo de Gauss-->



## Uso de herramientas computacionales 
La notación matricial ha sido una de las predilectas por las herramientas de cómputo. Por ejemplo MatLab, que significa laboratorio de matrices. En Python la librería `numpy` se ha especializado en las operaciones matriciales. 


In [ ]:
import numpy as np # Se llama la librería con el alias.

# se define en la matriz A

A=np.matrix([ 
    [11, 2,  3],
    [4,  15, 6],
    [7,  8,  19]
])
A

matrix([[11,  2,  3],
        [ 4, 15,  6],
        [ 7,  8, 19]])

In [ ]:
# Obtener un elemento de la matriz
# Renglón 0 y columna 0
# Recuerde que comienza desde cero

A[0,0]

11

In [ ]:
# Obtener un elemento de la matriz
# Renglón 1 y columna 2
# Recuerde que comienza desde cero

A[1,2]

6

In [ ]:
# Obtener la columna 2 de la matriz

A[:,2]

matrix([[ 3],
        [ 6],
        [19]])

In [ ]:
# Obtener el renglón 1 de la matriz

A[1,:]

matrix([[ 4, 15,  6]])

In [ ]:
# Obtener los renglones 0 y 2

A[[0,2],:]

matrix([[11,  2,  3],
        [ 7,  8, 19]])

In [ ]:
# Obtener primero el renglón 2 y después el renglón 0

A[[2,0],:]

matrix([[ 7,  8, 19],
        [11,  2,  3]])

# Matriz extendida y los sistemas de ecuaciones 

Un sistema de ecuaciones como el siguiente, 

$\matrix{
a_{11} x_1 + a_{12} x_2 + \ldots + a_{1n} x_n &= b_1 \\
a_{21} x_1 + a_{22} x_2 + \ldots + a_{2n} x_n &= b_2 \\
&\vdots\\
a_{m1} x_1 + a_{m2} x_2 + \ldots + a_{mn} x_n &= b_m \\
}$

en el que las variables $x_j$ son desconocidas, se puede representar por medio de la siguiente **matriz extendida**.

$[A:\vec{b}]=\left[\matrix{
a_{11} & a_{12} & \ldots & a_{1n} & : & b_1 \\
a_{21} & a_{22} & \ldots & a_{2n} & : & b_2 \\
\vdots & \vdots & \ddots & \vdots & : & \vdots \\
a_{m1} & a_{m2} & \ldots & a_{mn} & : & b_m \\
}\right]$

En la izquierda de la matriz está la **matriz de coeficientes** $A$ y en la derecha de la matriz está el **vector de términos constantes** (VTC) $\vec{b}$.


$A=\left[\matrix{
a_{11} & a_{12} & \ldots & a_{1n}  \\
a_{21} & a_{22} & \ldots & a_{2n}  \\
\vdots & \vdots & \ddots & \vdots  \\
a_{m1} & a_{m2} & \ldots & a_{mn}  \\
}\right]$, 
$\vec{b}=\left[\matrix{
 b_1 \\
 b_2 \\
 \vdots \\
 b_m \\
}\right]$



## Definiciones 
Las siguientes definiciones son para una matriz $A$ o para una matriz extendida $[A:\vec{b}]$

* Un __renglón de ceros__ sólo tiene ceros. 
* El __elemento delantero__ de un renglón no cero, está en el primer elemento a la izquierda diferente de cero. 
Por ejemplo, el sistema 

ecuaciones 
\begin{align}
0 x_0 + 3 x_1 + 0 x_2 + 1 x_3 &= 5 \\
0 x_0 + 0 x_1 + 0 x_2 + 0 x_3 &= 0\\
2 x_0 + 1 x_1 + 0 x_2 + 2 x_3 &= 6\\
0 x_0 + 0 x_1 + 0 x_2 + 1 x_3 &= 0\\
0 x_0 + 0 x_1 + 0 x_2 + 0 x_3 &= 3\\
\end{align}

ordenando las variable alfabéticamente la matriz extendida corresponde a 

\begin{align}
\begin{bmatrix}
	0 & 3 & 0 & 1 & : & 5\\
	0 & 0 & 0 & 0 & : & 0\\
	2 & 1 & 0 & 2 & : & 6\\
	0 & 0 & 0 & 1 & : & 0\\
	0 & 0 & 0 & 0 & : & 3
\end{bmatrix}
\end{align}

*	El elemento delantero del renglón 0 está en $x_1$. 
*	El renglón 1 es un renglón de ceros y no tiene elemento delantero. 
*	El elemento delantero del renglón 2 está en $x_0$. 
*	La variable delantera del renglón 3 está en $x_3$. 
*	En el renglón 4 el elemento delantero está en el término constante. 
	

## Clasificación de matrices extendidas
### E1
'Los renglones de ceros están en la parte inferior de la matriz o no hay renglones de ceros.'

El ejemplo tiene sólo un renglón de ceros que está al final, por lo tanto, cumple E1.

\begin{align*}
\begin{aligned}
	0 x_0 + 0 x_1 + 0 x_2 + 0 x_3 &= 3\\
	0 x_0 + 3 x_1 + 0 x_2 + 1 x_3 &= 5 \\
	0 x_0 + 0 x_1 + 0 x_2 + 1 x_3 &= 0\\
	2 x_0 + 1 x_1 + 0 x_2 + 2 x_3 &= 6\\
	0 x_0 + 0 x_1 + 0 x_2 + 0 x_3 &= 0
\end{aligned} \ \ \ \ \ \ 
	\begin{bmatrix}
		0 & 0 & 0 & 0 & : & 3\\
		0 & 3 & 0 & 1 & : & 5\\
		0 & 0 & 0 & 1 & : & 0\\
		2 & 1 & 0 & 2 & : & 6\\
		0 & 0 & 0 & 0 & : & 0
	\end{bmatrix}
\end{align*}

### E2

'Para cada elemento delantero $a_{i,j}$ se tiene que el elemento delantero del siguiente renglón $a_{i+1,k}$ (si lo hay) debe estar a la derecha (es decir $j < k$).'

En el siguiente ejemplo, los elementos de las variables $x_1$ y $x_3$ están abajo a la derecha de $x_0$ y $x_1$ respectivamente, por lo tanto, cumple E2.

\begin{align*}
	\begin{aligned}
		2 x_0 + 1 x_1 + 2 x_2 + 2 x_3 &= 6\\
		0 x_0 + 3 x_1 + 4 x_2 + 1 x_3 &= 5 \\
		0 x_0 + 0 x_1 + 0 x_2 + 1 x_3 &= 0\\
		0 x_0 + 0 x_1 + 0 x_2 + 0 x_3 &= 3\\
		0 x_0 + 0 x_1 + 0 x_2 + 0 x_3 &= 0
	\end{aligned} \ \ \
	\begin{bmatrix}
		2 & 1 & 2 & 2 & : & 6\\
		0 & 3 & 4 & 1 & : & 5\\
		0 & 0 & 0 & 1 & : & 0\\
		0 & 0 & 0 & 0 & : & 3\\
		0 & 0 & 0 & 0 & : & 0
	\end{bmatrix}
\end{align*}

* Una matriz está en forma (renglón) __escalón__ si cumple (E1) y (E2).
* La ubicación de cada elemento delantero de una <u>matriz escalón</u> se le llama __pivote__.
* La variable asociada a un pivote (si la hay) se llama __variable delantera__.
* Una variable que no es delantera se llama __variable libre__.  



#### Propiedades
1. En cada columna y en cada renglón de una matriz hay máximo un pivote.
2. El número de pivotes de una matriz $A_{m \times n}$ es menor o igual que $m$ y que $n$.
3. Si en la columna de términos constantes de una matriz extendida hay un <u>elemento delantero</u>, el sistema es __inconsistente__.
4. Si la columna de términos constantes de una matriz extendida  <u>escalón</u> está <u>sin pivote</u> (elemento delantero) entonces el sistema es __consistente__. 
5. Si una matriz extendida <u>escalón</u> tiene <u>pivotes</u> en cada columna menos en la de terminos constantes entonces el sistema tiene __solución única__.
6. Si una matriz extendida <u>escalón</u> tiene otra columna además de la de terminos constantes <u>sin pivote</u>  entonces el sistema tiene __infinitas soluciones__. 

Ejemplo:
\begin{align*}
	\begin{bmatrix}
        2 & 1 & 2 & 2 & : & 6\\
        0 & 3 & 4 & 1 & : & 5\\
        0 & 3 & 4 & 1 & : & 0\\
        0 & 0 & 0 & 0 & : & 3
	\end{bmatrix}
	\begin{bmatrix}
        2 & 1 & 2 & 2 & : & 6\\
        0 & 3 & 4 & 1 & : & 5\\
        0 & 0 & 0 & 1 & : & 0\\
        0 & 0 & 0 & 0 & : & 0
	\end{bmatrix}
	\begin{bmatrix}
        2 & 1 & 2 & 2 & : & 6\\
        0 & 3 & 4 & 1 & : & 5\\
        0 & 0 & 1 & 1 & : & 0\\
        0 & 0 & 0 & 3 & : & 0
	\end{bmatrix}
	\begin{bmatrix}
        2 & 1 & 2 & 2 & : & 6\\
        0 & 3 & 4 & 1 & : & 5\\
        2 & 4 & 6 & 3 & : & 0\\
        0 & 0 & 0 & 0 & : & 0
	\end{bmatrix}
\end{align*}

La primera matriz extendida es inconsistente ya que tiene un elemento delantero en los términos constantes.

Las matrices extendidas segunda y tercera son consistentes ya que están en forma escalón y sus pivotes no son términos constantes. La segunda matriz tiene infinitas soluciones ya que tiene al menos una variable libre. La tercera matriz tiene solución única ya que no tiene variables libres.

Para la cuarta matriz extendida, no podemos afirmar a priori que sea inconsistente, porque no tiene elementos delanteros en los términos constantes. Tampoco podemos afirmar a priori que sea consistente, ya que no está en forma escalón.   

### E3
'Cada elemento delantero es $1$ (y se llama __1 delantero__).'

En [Gro06] se define una matriz __escalonada__ (por renglones) como la matriz que cumple (E1), (E2) y (E3).

La siguiente matriz es un ejemplo de una matriz escalonada.

\begin{align*}
	\begin{aligned}
		1 x_0 + 1 x_1 + 2 x_2 + 2 x_3 &= 6\\
		0 x_0 + 1 x_1 + 4 x_2 + 1 x_3 &= 5 \\
		0 x_0 + 0 x_1 + 0 x_2 + 1 x_3 &= 0\\
		0 x_0 + 0 x_1 + 0 x_2 + 0 x_3 &= 0\\
		0 x_0 + 0 x_1 + 0 x_2 + 0 x_3 &= 0
	\end{aligned} \ \ \
	\begin{bmatrix}
		1 & 1 & 2 & 2 & : & 6\\
		0 & 1 & 4 & 1 & : & 5\\
		0 & 0 & 0 & 1 & : & 0\\
		0 & 0 & 0 & 0 & : & 0\\
		0 & 0 & 0 & 0 & : & 0
	\end{bmatrix}
\end{align*}

¿Cuál es la ventaja de E3?

### E4

'Arriba y abajo de cada elemento delantero hay ceros.'

Una matriz está en forma __escalón reducida__ o es __escalonada reducida__ si cumple (E1), (E2), (E3) y (E4).

La siguiente matriz es un ejemplo de una matriz reducida.

$$\begin{aligned}
		1 x_0 + 0 x_1 + 2 x_2 + 0 x_3 &= 6\\
		0 x_0 + 1 x_1 + 4 x_2 + 0 x_3 &= 5 \\
		0 x_0 + 0 x_1 + 0 x_2 + 1 x_3 &= 0\\
		0 x_0 + 0 x_1 + 0 x_2 + 0 x_3 &= 0\\
		0 x_0 + 0 x_1 + 0 x_2 + 0 x_3 &= 0
	\end{aligned} \ \ \ 
    	\begin{bmatrix}
		1 & 0 & 2 & 0 & : & 6\\
		0 & 1 & 4 & 0 & : & 5\\
		0 & 0 & 0 & 1 & : & 0\\
		0 & 0 & 0 & 0 & : & 0\\
		0 & 0 & 0 & 0 & : & 0
	\end{bmatrix}$$

En las matrices en escalón reducida, las variables delanteras se encuentran prácticamente despejadas y están en función de las variables libres (a estas últimas hay que asignarle parámetros). Lo cual se puede observar en el ejemplo anterior.
\begin{align}
x_2&=t\\
x_3&=0\\
x_1&=5-4t\\
x_0&=6-2t
\end{align}



# Operaciones elementales
[Nakos, Sec. 1.1]

Las siguientes operaciones entre los renglones de una matriz: 
* Intercambio de renglón. $R_i \leftrightarrow R_j$ 
* Multiplica un renglones por un escalar (diferente de cero). $kR_i \rightarrow R_i$ 
* Suma un múltiplo (no nulo) de un renglón a otro. $kR_j + R_i \rightarrow R_i$ 

se llaman __operaciones elementales__ y cumplen que:
* no alteran la solución del sistema de ecuaciones,
* permiten modificar la matriz para que cumplan las propiedades E1, E2, E3 y E4. 

La operación $k_jR_j + k_iR_i \rightarrow R_i$ corresponde a realizar:
* primero  $k_iR_i \rightarrow R_i$, 
* luego $k_jR_j + R_i \rightarrow R_i$. 

Dos matrices se dice que son __equivalentes__ si es posible pasar de una a la otra por medio de operaciones elementales y se denota $A \sim B$.  

A continuación, se dan ejemplos de las operaciones elementales.

In [ ]:
B = np.matrix([
    [0, 3, -6, ],
    [-1, 3, -10],
    [4, -9, 34],
    [2, -6, 20]
])

B

matrix([[  0,   3,  -6],
        [ -1,   3, -10],
        [  4,  -9,  34],
        [  2,  -6,  20]])

In [ ]:
# Intercambiar el renglón 0 con el renglón 3, 
# R0 <-> R3

B[[0,3],:] = B[[3,0],:]
B

matrix([[  2,  -6,  20],
        [ -1,   3, -10],
        [  4,  -9,  34],
        [  0,   3,  -6]])

In [ ]:
# Multiplicar el renglón 0  por un 1/2, 
# (1/2)R0 -> R0

B[0,:] *= 1/2   #  B[0,:] = B[0,:]*1/2
B

matrix([[  1,  -3,  10],
        [ -1,   3, -10],
        [  4,  -9,  34],
        [  0,   3,  -6]])

In [ ]:
# Suma (-4) veces el renglón 0 al renglón 2, 
# -4R0 + R2 -> R2

B[2,:] += -4*B[0,:]  #  B[2,:] = B[2,:] + (-4)*B[0,:]
B

matrix([[  1,  -3,  10],
        [ -1,   3, -10],
        [  0,   3,  -6],
        [  0,   3,  -6]])

# Operaciones no idempotentes y las celdas de Jupyter
Una operación es **idempotente** si da lo mismo realizarla una vez o más de una vez. Por ejemplo, el valor absoluto es una operación idempotente. Pero el cambio de signo no es una operación idempotente.

Las operaciones entre renglones usualmente no son operaciones idempotentes, entonces si usted ejecuta la celda de Jupyter dos veces, realizará dos veces la operación elemental y eso puede ser un inconveniente. 

Para solucionar ese problema es mejor que <u>**ejecute todas las celdas**</u>, para eso le recomiendo usar la opción que hay en el menú de ejecutar todo.  

# Si debe cambiar una operación elemental, antes de ejecutarla debe ejecutar TODAS las celdas ANTERIORES.  

Quiero recordar que las variables en Jupyter se actualizan en el orden en que se ejecutan las celdas. Si usted ejecuta las celdas en desorden las variables pueden tener valores inesperados. Es por esto mi insistencia en el uso de la opción del menú que <u>ejecuta todas las celdas</u>.

# Eliminación de Gauss
[Nakos, Sec. 1.2]


Una matriz se puede transformar a la forma escalón mediante los siguientes cuatro pasos. El último paso la convierte a la forma escalón reducida.
1. Vaya a la columna extrema izquierda que no sea de ceros.
2. Si el primer renglón tiene un cero en la columna del paso (1), intercámbielo con uno que tenga un elemento no cero en la misma columna.
3. Obtenga ceros debajo del elemento delantero, sumando múltiplos adecuados del renglón superior a los renglones debajo de él.
4. Cubra el renglón superior y repita el mismo proceso comenzando por el paso (1) aplicado a la sub-matriz restante. Repita este proceso con el resto de los renglones.
5. Comenzando con el último renglón no cero, avance hacia arriba: para cada renglón obtenga un 1 delantero e introduzca ceros arriba de él, sumando múltiplos adecuados a los renglones correspondientes. 

## Ejemplo

Utilizando el algoritmo de Gauss, encuentre la solución general del siguiente sistema de ecuaciones. En la variable `respuesta_ejemplo` asigne una tupla con la tupla de la solución particular trivial y las tuplas de las soluciones particulares básicas, si existen, cómo se realizó en el taller de sistemas de ecuaciones escalón.

$\matrix{
0a + 3b - 6c - 4d - 3e = -5\\
-1a + 3b - 10c - 4d - 4e = -2\\
4a - 9b + 34c + 0d + 1e = -21\\
2a - 6b + 20c + 2d + 8e = -8}$

## Solución



In [ ]:
C=np.matrix([
    [0,  3,  -6, -4, -3, -5 ],
    [-1, 3, -10, -4, -4, -2 ],
    [4, -9,  34,  0,  1, -21],
    [2, -6,  20,  2,  8, -8 ]
])
C

matrix([[  0,   3,  -6,  -4,  -3,  -5],
        [ -1,   3, -10,  -4,  -4,  -2],
        [  4,  -9,  34,   0,   1, -21],
        [  2,  -6,  20,   2,   8,  -8]])

Como el elemento `C[0,0]` es un 0, y bajo él hay elementos diferentes de cero es necesario cambiar el renglón 0 por otro renglón. Se escogió el renglón 1 ya que bajo el cero hay un -1, el cual divide al 4 a al 2 que también están bajo el 0.  

In [ ]:
#R1<->R0
C[[0,1],:]=C[[1,0],:]
C

matrix([[ -1,   3, -10,  -4,  -4,  -2],
        [  0,   3,  -6,  -4,  -3,  -5],
        [  4,  -9,  34,   0,   1, -21],
        [  2,  -6,  20,   2,   8,  -8]])

Ahora hay que eliminar los elementos diferentes de cero que están bajo el -1. Primero se elimina el 4. Sumando al renglón 2, 4 veces el renglón 0.  

In [ ]:
# 4R0 + R2 -> R2
C[2,:] += 4*C[0,:]      # C[2,:] = C[2,:] + 4*C[0,:]
C

matrix([[ -1,   3, -10,  -4,  -4,  -2],
        [  0,   3,  -6,  -4,  -3,  -5],
        [  0,   3,  -6, -16, -15, -29],
        [  2,  -6,  20,   2,   8,  -8]])

Ahora hay que eliminar el 2 que está bajo el -1. Sumando al renglón 3, 2 veces el renglón 0.  

In [ ]:
# 2R0 + R3 -> R3
C[3,:] += 2*C[0,:]
C

matrix([[ -1,   3, -10,  -4,  -4,  -2],
        [  0,   3,  -6,  -4,  -3,  -5],
        [  0,   3,  -6, -16, -15, -29],
        [  0,   0,   0,  -6,   0, -12]])

El -1 va a ser el pivote de la columna 0 y del renglón 0. 

Ahora pasamos a la segunda columna e ignoramos el renglón 0. Con `C[1,1]`, que es un 3, se elimina el contenido de `C[2,1]`, que es otro 3. Para hacer esto, basta con restarle el renglón 1 al renglón 2. 

In [ ]:
# -R1 + R2 -> R2
C[2,:] += -C[1,:]
C

matrix([[ -1,   3, -10,  -4,  -4,  -2],
        [  0,   3,  -6,  -4,  -3,  -5],
        [  0,   0,   0, -12, -12, -24],
        [  0,   0,   0,  -6,   0, -12]])

El 3 de `C[1,1]` va a ser el pivote de la columna 1 y del renglón 1. 

Ahora ignoramos el renglón 0 y el renglón 1. Al pasar a la columna 2, la que tiene en los renglones ignorados -10 y -6, vemos que en los otros renglones sólo tiene ceros, por lo tanto esta columna no tendrá pivote. 

La columna 2 no va a tener pivote.

In [ ]:
C

matrix([[ -1,   3, -10,  -4,  -4,  -2],
        [  0,   3,  -6,  -4,  -3,  -5],
        [  0,   0,   0, -12, -12, -24],
        [  0,   0,   0,  -6,   0, -12]])

Al ver la columna 3, en los dos últimos renglones hay un -12 y un -6. Con el -12 hay que eliminar el -6. Una forma es sumar el renglón 2  a menos dos veces el renglón 3. Esta no es una operación elemental ya que el renglón de destino se multiplica por -2. Pero es equivalente a dos operaciones elementales, como se explicó anteriormente.

In [ ]:
# R2 - 2R3 -> R3
C[3,:] = C[2,:] + (-2)*C[3,:] 
C

matrix([[ -1,   3, -10,  -4,  -4,  -2],
        [  0,   3,  -6,  -4,  -3,  -5],
        [  0,   0,   0, -12, -12, -24],
        [  0,   0,   0,   0, -12,   0]])

Con esto hemos obtenido una <u>matriz escalón</u>. Con lo cual se pueden ubicar los pivotes en `C[0,0]`, `C[1,1]`, `C[2,3]` y en `C[3,4]`.

Ahora se puede continuar con el proceso hasta obtener una matriz reducida.

In [ ]:
# -(1/12)R3 -> R3

C[3,:] *= -1/12
C

matrix([[ -1,   3, -10,  -4,  -4,  -2],
        [  0,   3,  -6,  -4,  -3,  -5],
        [  0,   0,   0, -12, -12, -24],
        [  0,   0,   0,   0,   1,   0]])

In [ ]:
C[2,:] += 12*C[3] # 12 R3 + R2 -> R2
C[1,:] += 3*C[3]  # 3  R3 + R1 -> R1
C[0,:] += 4*C[3]  # 4  R3 + R0 -> R0
C

matrix([[ -1,   3, -10,  -4,   0,  -2],
        [  0,   3,  -6,  -4,   0,  -5],
        [  0,   0,   0, -12,   0, -24],
        [  0,   0,   0,   0,   1,   0]])

In [ ]:
# -(1/12)R2 -> R2

C[2,:] *= -1/12  
C

matrix([[ -1,   3, -10,  -4,   0,  -2],
        [  0,   3,  -6,  -4,   0,  -5],
        [  0,   0,   0,   1,   0,   2],
        [  0,   0,   0,   0,   1,   0]])

In [ ]:
C[1,:] += 4*C[2] # 4 R2 + R1 -> R1
C[0,:] += 4*C[2] # 4 R2 + R0 -> R0
C

matrix([[ -1,   3, -10,   0,   0,   6],
        [  0,   3,  -6,   0,   0,   3],
        [  0,   0,   0,   1,   0,   2],
        [  0,   0,   0,   0,   1,   0]])

In [ ]:
# (1/3)R1 -> R1

C[1,:] *= 1/3
C

matrix([[ -1,   3, -10,   0,   0,   6],
        [  0,   1,  -2,   0,   0,   1],
        [  0,   0,   0,   1,   0,   2],
        [  0,   0,   0,   0,   1,   0]])

In [ ]:
# R0 - 3R1 -> R1

C[0,:] += -3*C[1]
C

matrix([[-1,  0, -4,  0,  0,  3],
        [ 0,  1, -2,  0,  0,  1],
        [ 0,  0,  0,  1,  0,  2],
        [ 0,  0,  0,  0,  1,  0]])

In [ ]:
# -R0 -> R0

C[0,:] *= -1
C

matrix([[ 1,  0,  4,  0,  0, -3],
        [ 0,  1, -2,  0,  0,  1],
        [ 0,  0,  0,  1,  0,  2],
        [ 0,  0,  0,  0,  1,  0]])

La anterior matriz ya se encuentra reducida. El sistema de ecuaciones que le corresponde es el siguiente.

$\matrix{
1a + 0b + 4c + 0d + 0e =-3\\
0a + 1b - 2c + 0d + 0e = 1\\
0a + 0b + 0c + 1d + 0e = 2\\
0a + 0b + 0c + 0d + 1e = 0}$



La única variable libre es $c=t$.

Ahora despejamos las variables delanteras de abajo hacia arriba:

$\matrix{
e=0\\
d=2\\
b=1+2t\\
a=-3-4t}$

Por lo tanto la solución general es

$\left( \matrix{a \\ b \\ c \\ d \\ e} \right)
=\left( \matrix{-3 \\1  \\0  \\2  \\0   } \right)
+t\left( \matrix{-4 \\2  \\1  \\0  \\ 0  } \right)
$

La solución particular trivial es
$\left( \matrix{-3 \\1  \\0  \\2  \\0   } \right)
+0\left( \matrix{-4 \\2  \\1  \\0  \\ 0  } \right)
=\left( \matrix{-3 \\1  \\0  \\2  \\0   } \right)
$

Como sólo hay un parámetro entonces sólo hay una solución particular básica 
$\left( \matrix{-3 \\1  \\0  \\2  \\0   } \right)
+1\left( \matrix{-4 \\2  \\1  \\0  \\ 0  } \right)
=\left( \matrix{-7 \\3  \\1  \\2  \\0   } \right)
$

A continuación verificamos que ambas soluciones particulares cumplan con las 4 ecuaciones. Comenzamos probando la solución particular trivial.

In [ ]:
(a, b, c, d, e)=(-3, 1, 0, 2, 0)
(a, b, c, d, e)

(-3, 1, 0, 2, 0)

In [ ]:
0*a + 3*b - 6*c - 4*d - 3*e ==-5


True

In [ ]:
-1*a + 3*b -10*c - 4*d - 4*e == -2 

True

In [ ]:
4*a - 9*b + 34*c + 0*d + 1*e == -21


True

In [ ]:
2*a - 6*b + 20*c + 2*d + 8*e == -8 

True

Ahora verificamos la solución particular básica

In [ ]:
(a, b, c, d, e)=(-7, 3, 1, 2, 0 )
(a, b, c, d, e)

(-7, 3, 1, 2, 0)

In [ ]:
0*a + 3*b - 6*c - 4*d - 3*e ==-5


True

In [ ]:
-1*a + 3*b -10*c - 4*d - 4*e == -2 

True

In [ ]:
4*a - 9*b + 34*c + 0*d + 1*e == -21


True

In [ ]:
2*a - 6*b + 20*c + 2*d + 8*e == -8 

True

Luego de verificar los resultados escribimos la respuesta del ejercicio.

In [ ]:
respuesta_ejemplo=(
    (-3, 1, 0, 2, 0),    
    (-7, 3, 1, 2, 0)
)

respuesta_ejemplo

((-3, 1, 0, 2, 0), (-7, 3, 1, 2, 0))

Recuerde que
# Si debe cambiar una operación elemental, antes de ejecutarla debe <u>ejecutar TODAS las celdas ANTERIORES</u>.

In [ ]:
nombre= '  escriba aquí su nombre   '
código=0    # reemplazar el cero por su cógdio

## Ejercicio

Utilizando el algoritmo de Gauss, encuentre:
* la solución general del siguiente sistema de ecuaciones. 
* En la variable `respuesta_ejercicio` asigne una tupla con la tupla de la solución particular trivial y las tuplas de las soluciones particulares básicas, si existen, como se realizó en el taller de sistemas de ecuaciones escalón.

$\matrix{
-2x_1 + ax_2 - bx_3 - (a+1)x_4 - (b-1)x_5 = -5\\
0x_1 + 0x_2 - 10x_3 - 4x_4 - 4x_5 = -2\\
6x_1 - 9x_2 + 34x_3 + 0x_4 + 1x_5 = -21}$

Recuerde que $a$ es el último dígito de su código y que $b$ es el penúltimo dígito de su código.

In [ ]:
respuesta_ejercicio=(
)