<a href="https://colab.research.google.com/github/GerardoMunoz/PresentacionesAlgebraLineal/blob/main/AL06_OpElem.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



# Matriz Extendida
<!--## Aplicaciones
## Equivalencia con sistema de ecuacioes
## E1 a E4
## Operaciones elementales
## Algoritmo de Gauss-->



# Notación
Así como durante el <u>primer</u> año de vida tenemos <u>cero</u> años, también en las matrices el primer renglon es el renglon cero, bueno al menos en Python y otros lenguajes de programación. 

$$\begin{matrix}\text{renglón 0}\\\text{renglón 1}\\\text{renglón 2}\end{matrix}\begin{bmatrix}a&b&c&:&x\\d&e&f&:&y\\g&h&i&:&z\end{bmatrix}$$


Sin embargo, algunos lenguajes como Matlab llaman el <u>primer</u> renglón, el renglón <u>uno</u>. Esto último coincide con la notación de la mayoria de libros de álgebra lineal.

$$\begin{matrix}\text{renglón 1}\\\text{renglón 2}\\\text{renglón 3}\end{matrix}\begin{bmatrix}a&b&c&:&x\\d&e&f&:&y\\g&h&i&:&z\end{bmatrix}$$



En este curso usaremos ambas notaciones. Es por eso que si ha duda si el primer renglon es el renglón cero o el renglón uno lo invito a que pregunte para evitar confusiones.
En particular para la clase de HOY, como usaremos Python, llamaremos el <u>primer</u> renglón el renglón <u>cero</u>.

$$\begin{matrix}\text{renglón 0}\\\text{renglón 1}\\\text{renglón 2}\end{matrix}\begin{bmatrix}a&b&c&:&x\\d&e&f&:&y\\g&h&i&:&z\end{bmatrix}$$





# Operaciones elementales
[Nakos, Sec. 1.1]

Ahora veremos como resolver sistemas de ecuaciones que no cumplen con E1, E2, E3 o E4.

Para esto definiremos las siguientes  __operaciones elementales__  entre los renglones de una matriz extendida, que permiten modificar la matriz para que cumplan las propiedades E1, E2, E3 y E4. Pero lo más importante es que <u> no alteran la solución</u> del sistema de ecuaciones.

* **Intercambio de renglones**. $r_i \leftrightarrow r_j$

$$\begin{bmatrix}a&b&c&:&x\\d&e&f&:&y\\g&h&i&:&z\end{bmatrix}r_0 \leftrightarrow r_1\begin{bmatrix}d&e&f&:&y\\a&b&c&:&x\\g&h&i&:&z\end{bmatrix}$$

El intercambio de renglones no afecta la solución del sistema de ecuaciones ya que el orden de la ecuaciones no altera la solución. 

* **Multiplica un renglones por un escalar** (diferente de cero). $kr_i \rightarrow r_i$ 
$$\begin{bmatrix}a&b&c&:&x\\d&e&f&:&y\\g&h&i&:&z\end{bmatrix} 3r_2 \rightarrow r_2\begin{bmatrix}a&b&c&:&x\\d&e&f&:&y\\3g&3h&3i&:&3z\end{bmatrix}$$

Al multiplicar un renglón por una constante no se altera la solución ya que la respectiva ecuación se multiplica a ambos lados por la misma constante.

* **Suma un múltiplo (no nulo) de un renglón a otro**. $kr_j + 1r_i \rightarrow r_i$ 

Observe que el renglón de destino ($r_i$) es multiplicado por 1, mientras que el otro renglón ($r_j$) sí es multiplicado por $k$.

$$\begin{bmatrix}a&b&c&:&x\\d&e&f&:&y\\g&h&i&:&z\end{bmatrix} 3r_2 + r_1  \rightarrow r_1\begin{bmatrix}a&b&c&:&x\\3g+d&3h+e&3i+f&:&3z+y\\g&h&i&:&z\end{bmatrix}$$

En las siguientes páginas el profesor Von Schmohawk visualiza esta operación en  $\mathbb{R}^2$ y en $\mathbb{R}^3$. En este curso más adelante veremos el tema de la visualización. 

* https://www.youtube.com/watch?v=fGq07lDUb9k&list=PL20023FA07684B937&index=38
* https://www.youtube.com/watch?v=cB2t5VIVHZI&list=PL20023FA07684B937&index=48

# Una operación no tan elementental

La operación $k_jr_j + k_ir_i \rightarrow r_i$ corresponde a realizar:
* primero  $k_ir_i \rightarrow r_i$, 
* luego $k_jr_j + r_i \rightarrow r_i$. 

$$\begin{bmatrix}a&b&c&:&x\\d&e&f&:&y\\g&h&i&:&z\end{bmatrix} 3r_2 + 4r_1  \rightarrow r_1\begin{bmatrix}a&b&c&:&x\\3g+4d&3h+4e&3i+4f&:&3z+4y\\g&h&i&:&z\end{bmatrix}$$

# Equivalencia de matrices
Dos matrices se dice que son __equivalentes__ si es posible pasar de una a la otra por medio de operaciones elementales y se denota $A \sim B$.  



## Uso de herramientas computacionales 

A continuación usaremos la librería `sympy` de Python que permite realizar operaciones matriciales.

In [ ]:
import sympy as sp # Se llama la librería `sympy` con el alias `sp`.

# se define en la matriz `A`

A=np.matrix([ 
    [11, 2,  3],
    [4,  15, 6],
    [7,  8,  19]
])
A

matrix([[11,  2,  3],
        [ 4, 15,  6],
        [ 7,  8, 19]])

In [ ]:
# Obtener un elemento de la matriz
# Renglón 0 y columna 0
# Recuerde que comienza desde cero

A[0,0]

11

In [ ]:
# Obtener un elemento de la matriz
# Renglón 1 y columna 2
# Recuerde que comienza desde cero

A[1,2]

6

In [ ]:
# Obtener la columna 2 de la matriz

A[:,2]

matrix([[ 3],
        [ 6],
        [19]])

In [ ]:
# Obtener el renglón 1 de la matriz

A[1,:]

matrix([[ 4, 15,  6]])

In [ ]:
# Obtener los renglones 0 y 2

A[[0,2],:]

matrix([[11,  2,  3],
        [ 7,  8, 19]])

In [ ]:
# Obtener primero el renglón 2 y después el renglón 0

A[[2,0],:]

matrix([[ 7,  8, 19],
        [11,  2,  3]])

In [ ]:
B = np.matrix([
    [0, 3, -6, ],
    [-1, 3, -10],
    [4, -9, 34],
    [2, -6, 20]
])

B

matrix([[  0,   3,  -6],
        [ -1,   3, -10],
        [  4,  -9,  34],
        [  2,  -6,  20]])

In [ ]:
# Intercambiar el renglón 0 con el renglón 3, 
# R0 <-> R3

B[[0,3],:] = B[[3,0],:]
B

matrix([[  2,  -6,  20],
        [ -1,   3, -10],
        [  4,  -9,  34],
        [  0,   3,  -6]])

In [ ]:
# Multiplicar el renglón 0  por un 1/2, 
# (1/2)R0 -> R0

B[0,:] *= 1/2   #  B[0,:] = B[0,:]*1/2
B

matrix([[  1,  -3,  10],
        [ -1,   3, -10],
        [  4,  -9,  34],
        [  0,   3,  -6]])

In [ ]:
# Suma (-4) veces el renglón 0 al renglón 2, 
# -4R0 + R2 -> R2

B[2,:] += -4*B[0,:]  #  B[2,:] = B[2,:] + (-4)*B[0,:]
B

matrix([[  1,  -3,  10],
        [ -1,   3, -10],
        [  0,   3,  -6],
        [  0,   3,  -6]])

# Operaciones no idempotentes y las celdas de Jupyter
Una operación es **idempotente** si da lo mismo realizarla una vez o más de una vez. Por ejemplo, el valor absoluto es una operación idempotente. Pero el cambio de signo no es una operación idempotente.

Las operaciones entre renglones usualmente no son operaciones idempotentes, entonces si usted ejecuta la celda de Jupyter dos veces, realizará dos veces la operación elemental y eso puede ser un inconveniente. 

Para solucionar ese problema es mejor que <u>**ejecute todas las celdas**</u>, para eso le recomiendo usar la opción que hay en el menú de ejecutar todo.  

# Si debe cambiar una operación elemental, antes de ejecutarla debe ejecutar TODAS las celdas ANTERIORES.  

Quiero recordar que las variables en Jupyter se actualizan en el orden en que se ejecutan las celdas. Si usted ejecuta las celdas en desorden las variables pueden tener valores inesperados. Es por esto mi insistencia en el uso de la opción del menú que <u>ejecuta todas las celdas</u>.

# Eliminación de Gauss
[Nakos, Sec. 1.2]


Una matriz se puede transformar a la forma escalón mediante los siguientes cuatro pasos. El último paso la convierte a la forma escalón reducida.
1. Vaya a la columna extrema izquierda que no sea de ceros.
2. Si el primer renglón tiene un cero en la columna del paso (1), intercámbielo con uno que tenga un elemento no cero en la misma columna.
3. Obtenga ceros debajo del elemento delantero, sumando múltiplos adecuados del renglón superior a los renglones debajo de él.
4. Cubra el renglón superior y repita el mismo proceso comenzando por el paso (1) aplicado a la sub-matriz restante. Repita este proceso con el resto de los renglones.
5. Comenzando con el último renglón no cero, avance hacia arriba: para cada renglón obtenga un 1 delantero e introduzca ceros arriba de él, sumando múltiplos adecuados a los renglones correspondientes. 

## Ejemplo

Utilizando el algoritmo de Gauss, encuentre la solución general del siguiente sistema de ecuaciones. En la variable `respuesta_ejemplo` asigne una tupla con la tupla de la solución particular trivial y las tuplas de las soluciones particulares básicas, si existen, cómo se realizó en el taller de sistemas de ecuaciones escalón.

$\matrix{
0a + 3b - 6c - 4d - 3e = -5\\
-1a + 3b - 10c - 4d - 4e = -2\\
4a - 9b + 34c + 0d + 1e = -21\\
2a - 6b + 20c + 2d + 8e = -8}$

## Solución



In [ ]:
C=np.matrix([
    [0,  3,  -6, -4, -3, -5 ],
    [-1, 3, -10, -4, -4, -2 ],
    [4, -9,  34,  0,  1, -21],
    [2, -6,  20,  2,  8, -8 ]
])
C

matrix([[  0,   3,  -6,  -4,  -3,  -5],
        [ -1,   3, -10,  -4,  -4,  -2],
        [  4,  -9,  34,   0,   1, -21],
        [  2,  -6,  20,   2,   8,  -8]])

Como el elemento `C[0,0]` es un 0, y bajo él hay elementos diferentes de cero es necesario cambiar el renglón 0 por otro renglón. Se escogió el renglón 1 ya que bajo el cero hay un -1, el cual divide al 4 a al 2 que también están bajo el 0.  

In [ ]:
#R1<->R0
C[[0,1],:]=C[[1,0],:]
C

matrix([[ -1,   3, -10,  -4,  -4,  -2],
        [  0,   3,  -6,  -4,  -3,  -5],
        [  4,  -9,  34,   0,   1, -21],
        [  2,  -6,  20,   2,   8,  -8]])

Ahora hay que eliminar los elementos diferentes de cero que están bajo el -1. Primero se elimina el 4. Sumando al renglón 2, 4 veces el renglón 0.  

In [ ]:
# 4R0 + R2 -> R2
C[2,:] += 4*C[0,:]      # C[2,:] = C[2,:] + 4*C[0,:]
C

matrix([[ -1,   3, -10,  -4,  -4,  -2],
        [  0,   3,  -6,  -4,  -3,  -5],
        [  0,   3,  -6, -16, -15, -29],
        [  2,  -6,  20,   2,   8,  -8]])

Ahora hay que eliminar el 2 que está bajo el -1. Sumando al renglón 3, 2 veces el renglón 0.  

In [ ]:
# 2R0 + R3 -> R3
C[3,:] += 2*C[0,:]
C

matrix([[ -1,   3, -10,  -4,  -4,  -2],
        [  0,   3,  -6,  -4,  -3,  -5],
        [  0,   3,  -6, -16, -15, -29],
        [  0,   0,   0,  -6,   0, -12]])

El -1 va a ser el pivote de la columna 0 y del renglón 0. 

Ahora pasamos a la segunda columna e ignoramos el renglón 0. Con `C[1,1]`, que es un 3, se elimina el contenido de `C[2,1]`, que es otro 3. Para hacer esto, basta con restarle el renglón 1 al renglón 2. 

In [ ]:
# -R1 + R2 -> R2
C[2,:] += -C[1,:]
C

matrix([[ -1,   3, -10,  -4,  -4,  -2],
        [  0,   3,  -6,  -4,  -3,  -5],
        [  0,   0,   0, -12, -12, -24],
        [  0,   0,   0,  -6,   0, -12]])

El 3 de `C[1,1]` va a ser el pivote de la columna 1 y del renglón 1. 

Ahora ignoramos el renglón 0 y el renglón 1. Al pasar a la columna 2, la que tiene en los renglones ignorados -10 y -6, vemos que en los otros renglones sólo tiene ceros, por lo tanto esta columna no tendrá pivote. 

La columna 2 no va a tener pivote.

In [ ]:
C

matrix([[ -1,   3, -10,  -4,  -4,  -2],
        [  0,   3,  -6,  -4,  -3,  -5],
        [  0,   0,   0, -12, -12, -24],
        [  0,   0,   0,  -6,   0, -12]])

Al ver la columna 3, en los dos últimos renglones hay un -12 y un -6. Con el -12 hay que eliminar el -6. Una forma es sumar el renglón 2  a menos dos veces el renglón 3. Esta no es una operación elemental ya que el renglón de destino se multiplica por -2. Pero es equivalente a dos operaciones elementales, como se explicó anteriormente.

In [ ]:
# R2 - 2R3 -> R3
C[3,:] = C[2,:] + (-2)*C[3,:] 
C

matrix([[ -1,   3, -10,  -4,  -4,  -2],
        [  0,   3,  -6,  -4,  -3,  -5],
        [  0,   0,   0, -12, -12, -24],
        [  0,   0,   0,   0, -12,   0]])

Con esto hemos obtenido una <u>matriz escalón</u>. Con lo cual se pueden ubicar los pivotes en `C[0,0]`, `C[1,1]`, `C[2,3]` y en `C[3,4]`.

Ahora se puede continuar con el proceso hasta obtener una matriz reducida.

In [ ]:
# -(1/12)R3 -> R3

C[3,:] *= -1/12
C

matrix([[ -1,   3, -10,  -4,  -4,  -2],
        [  0,   3,  -6,  -4,  -3,  -5],
        [  0,   0,   0, -12, -12, -24],
        [  0,   0,   0,   0,   1,   0]])

In [ ]:
C[2,:] += 12*C[3] # 12 R3 + R2 -> R2
C[1,:] += 3*C[3]  # 3  R3 + R1 -> R1
C[0,:] += 4*C[3]  # 4  R3 + R0 -> R0
C

matrix([[ -1,   3, -10,  -4,   0,  -2],
        [  0,   3,  -6,  -4,   0,  -5],
        [  0,   0,   0, -12,   0, -24],
        [  0,   0,   0,   0,   1,   0]])

In [ ]:
# -(1/12)R2 -> R2

C[2,:] *= -1/12  
C

matrix([[ -1,   3, -10,  -4,   0,  -2],
        [  0,   3,  -6,  -4,   0,  -5],
        [  0,   0,   0,   1,   0,   2],
        [  0,   0,   0,   0,   1,   0]])

In [ ]:
C[1,:] += 4*C[2] # 4 R2 + R1 -> R1
C[0,:] += 4*C[2] # 4 R2 + R0 -> R0
C

matrix([[ -1,   3, -10,   0,   0,   6],
        [  0,   3,  -6,   0,   0,   3],
        [  0,   0,   0,   1,   0,   2],
        [  0,   0,   0,   0,   1,   0]])

In [ ]:
# (1/3)R1 -> R1

C[1,:] *= 1/3
C

matrix([[ -1,   3, -10,   0,   0,   6],
        [  0,   1,  -2,   0,   0,   1],
        [  0,   0,   0,   1,   0,   2],
        [  0,   0,   0,   0,   1,   0]])

In [ ]:
# R0 - 3R1 -> R1

C[0,:] += -3*C[1]
C

matrix([[-1,  0, -4,  0,  0,  3],
        [ 0,  1, -2,  0,  0,  1],
        [ 0,  0,  0,  1,  0,  2],
        [ 0,  0,  0,  0,  1,  0]])

In [ ]:
# -R0 -> R0

C[0,:] *= -1
C

matrix([[ 1,  0,  4,  0,  0, -3],
        [ 0,  1, -2,  0,  0,  1],
        [ 0,  0,  0,  1,  0,  2],
        [ 0,  0,  0,  0,  1,  0]])

La anterior matriz ya se encuentra reducida. El sistema de ecuaciones que le corresponde es el siguiente.

$\matrix{
1a + 0b + 4c + 0d + 0e =-3\\
0a + 1b - 2c + 0d + 0e = 1\\
0a + 0b + 0c + 1d + 0e = 2\\
0a + 0b + 0c + 0d + 1e = 0}$



La única variable libre es $c=t$.

Ahora despejamos las variables delanteras de abajo hacia arriba:

$\matrix{
e=0\\
d=2\\
b=1+2t\\
a=-3-4t}$

Por lo tanto la solución general es

$\left( \matrix{a \\ b \\ c \\ d \\ e} \right)
=\left( \matrix{-3 \\1  \\0  \\2  \\0   } \right)
+t\left( \matrix{-4 \\2  \\1  \\0  \\ 0  } \right)
$

La solución particular trivial es
$\left( \matrix{-3 \\1  \\0  \\2  \\0   } \right)
+0\left( \matrix{-4 \\2  \\1  \\0  \\ 0  } \right)
=\left( \matrix{-3 \\1  \\0  \\2  \\0   } \right)
$

Como sólo hay un parámetro entonces sólo hay una solución particular básica 
$\left( \matrix{-3 \\1  \\0  \\2  \\0   } \right)
+1\left( \matrix{-4 \\2  \\1  \\0  \\ 0  } \right)
=\left( \matrix{-7 \\3  \\1  \\2  \\0   } \right)
$

A continuación verificamos que ambas soluciones particulares cumplan con las 4 ecuaciones. Comenzamos probando la solución particular trivial.

In [ ]:
(a, b, c, d, e)=(-3, 1, 0, 2, 0)
(a, b, c, d, e)

(-3, 1, 0, 2, 0)

In [ ]:
0*a + 3*b - 6*c - 4*d - 3*e ==-5


True

In [ ]:
-1*a + 3*b -10*c - 4*d - 4*e == -2 

True

In [ ]:
4*a - 9*b + 34*c + 0*d + 1*e == -21


True

In [ ]:
2*a - 6*b + 20*c + 2*d + 8*e == -8 

True

Ahora verificamos la solución particular básica

In [ ]:
(a, b, c, d, e)=(-7, 3, 1, 2, 0 )
(a, b, c, d, e)

(-7, 3, 1, 2, 0)

In [ ]:
0*a + 3*b - 6*c - 4*d - 3*e ==-5


True

In [ ]:
-1*a + 3*b -10*c - 4*d - 4*e == -2 

True

In [ ]:
4*a - 9*b + 34*c + 0*d + 1*e == -21


True

In [ ]:
2*a - 6*b + 20*c + 2*d + 8*e == -8 

True

Luego de verificar los resultados escribimos la respuesta del ejercicio.

In [ ]:
respuesta_ejemplo=(
    (-3, 1, 0, 2, 0),    
    (-7, 3, 1, 2, 0)
)

respuesta_ejemplo

((-3, 1, 0, 2, 0), (-7, 3, 1, 2, 0))

Recuerde que
# Si debe cambiar una operación elemental, antes de ejecutarla debe <u>ejecutar TODAS las celdas ANTERIORES</u>.

In [ ]:
nombre= '  escriba aquí su nombre   '
código=0    # reemplazar el cero por su cógdio

## Ejercicio

Utilizando el algoritmo de Gauss, encuentre:
* la solución general del siguiente sistema de ecuaciones. 
* En la variable `respuesta_ejercicio` asigne una tupla con la tupla de la solución particular trivial y las tuplas de las soluciones particulares básicas, si existen, como se realizó en el taller de sistemas de ecuaciones escalón.

$\matrix{
-2x_1 + ax_2 - bx_3 - (a+1)x_4 - (b-1)x_5 = -5\\
0x_1 + 0x_2 - 10x_3 - 4x_4 - 4x_5 = -2\\
6x_1 - 9x_2 + 34x_3 + 0x_4 + 1x_5 = -21}$

Recuerde que $a$ es el último dígito de su código y que $b$ es el penúltimo dígito de su código.

In [ ]:
respuesta_ejercicio=(
)